### PR TITLE
fix: only billing users can downgrade a plan

### LINKED ISSUE #11913: downgrade from Team plan fails silently
[A user](https://app.hubspot.com/contacts/3888472/record/0-1/46639076411) 🔒 wrote in to say that they couldn't downgrade from the Team plan. They provided the following information: 

> - Be on a paid plan (presumably Team)
> - Click to downgrade to free
> - Answer the reason for why the downgrade
> - Hit Submit, modal closes
> - Expected: Plan CTAs change to show free as 'current plan' and offer an option to upgrade back to Team plan
> - Actual: Modal closes with no apparent change to the plan. Refreshing doesn't help. In short, downgrade seems to silently fail.
> - About my setup: Macbook Air M1, latest MacOS, latest Safari

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #11913 

The UI was misleading in that it showed the downgrade button and dialog also for non-billing leaders which resulted in confusion as they aren't allowed to downgrade, so the mutation failed.

Additionally we tried to promote the user who upgraded initially to a billing user, but we were grabbing the userId from the server auth token. I added the userId to the subscription metadata so we can perform this promotion now successfully.

## Demo
https://www.loom.com/share/bbc19a3dfd62468a91d61a880ce81253?sid=c73e9cdc-df0f-4f96-9cad-19a16d3beb2e

## Testing

2 users: Billing leader Bob and Card holder Caren who's not billing leader

- [ ] Caren cannot downgrade from Team
  - upgrade to Team with Bob
  - go to billing page with Caren
  - see the Downgrade button disabled

- [ ] Caren is promoted to billing lead when upgrading to Team
  - downgrade to Starter
  - upgrade to Team with Caren
  - both Bob and Caren are no billing leads
  
## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/client/modules/userDashboard/components/OrgBilling/OrgPlan.tsx [hunk 1]
```diff
@@ -121,6 +121,7 @@ const CTAButton = styled(BaseButton)<{
 }>(({buttonStyle}) => ({
   width: '80%',
   boxShadow: buttonStyle === 'primary' ? Elevation.Z8 : Elevation.Z0,
+  opacity: 1,
```
Comment (Dschoordsch) [inline packages/client/modules/userDashboard/components/OrgBilling/OrgPlan.tsx:124]: Overwriting the disabled styles in base button. Would be better to use plain buttons here and style them from scratch, but I just wanted to be done with this fix.

File: packages/server/graphql/private/mutations/upgradeToTeamTier.ts [hunk 2]
```diff
@@ -44,21 +42,20 @@ const upgradeToTeamTier: MutationResolvers['upgradeToTeamTier'] = async (
   const subOptions = {mutatorId, operationId}
 
   // AUTH
-  const viewerId = getUserId(authToken)
```
Comment (Dschoordsch) [inline packages/server/graphql/private/mutations/upgradeToTeamTier.ts:47]: The mutation is called from the server so the `viewerId` would always be `'aGhostUser'`

File: packages/server/graphql/private/typeDefs/Mutation.graphql [hunk 3]
```diff
@@ -360,6 +360,20 @@ type Mutation {
 		subscriptionId: ID!
 	): Boolean
 
+	"""
+	Called on stripe.invoice.payment_succeeded webhook to move an org to the team tier
+	"""
+	upgradeToTeamTier(
```
Comment (Dschoordsch) [inline packages/server/graphql/private/typeDefs/Mutation.graphql:366]: The resolver was in private, so calling the mutation publicly wouldn't have worked anyways.

File: packages/server/utils/authorization.ts [hunk 4]
```diff
@@ -1,17 +1,27 @@
...
-export const getUserId = (authToken: any) => {
+const getUserIdInternal = (authToken: any) => {
   return authToken && typeof authToken === 'object' ? (authToken.sub as string) : ''
 }
 
+export const getUserId = (authToken: any) => {
+  const userId = getUserIdInternal(authToken)
+  if (userId === 'aGhostUser') {
+    // This probably means someone is trying to get the viewerId when the mutation was called from the server
+    logError(new Error('getUserId called with aGhostUser'))
```
Comment (Dschoordsch) [inline packages/server/utils/authorization.ts:14]: Logging this as error to avoid confusing the server token with the one from the viewer
