### PR TITLE
fix: catch OpenAI exceptions

### LINKED ISSUE #12011: bug: OpenAI failure bubbles up and crashes the app
An OpenAI request failed and caused the app to crash. The dataloader was in the trace, so it's most likely `aiLoaderMakers.meetingInsightsContent`, but we should catch errors everywhere.

https://app.datadoghq.com/logs?query=pod_name%3Aparabol-webserver-58f8fd6596-84ldn&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1757516687923&to_ts=1757516712423&live=false

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #12011
## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

File: packages/server/graphql/public/fields/pageInsights.ts [hunk 1]
```diff
@@ -121,43 +121,47 @@ If not, respond with "Invalid prompt"`
...
-    for await (const chunk of rawInsightResponseStream) {
-      const content = chunk.choices[0]?.delta?.content
-      if (content) {
-        yield content
-      } else if (chunk.usage) {
-        const tokenCost = chunk.usage?.total_tokens ?? 10_000
-        analytics.pageInsightsGenerated(viewer)
-        await pg.insertInto('AIRequest').values({userId: viewerId, tokenCost}).execute()
+    const streamIt = async function* () {
+      for await (const chunk of rawInsightResponseStream) {
```
Comment (Dschoordsch) [inline packages/server/graphql/public/fields/pageInsights.ts]: We probably want to try/catch this as well and abort the stream. Have to look up the syntax first
