### PR TITLE
Fix delete team validation

### LINKED ISSUE #1511: Archive team validation
## Bug

The team archive validation field does not require text at all, or the text to be the same exact string as the team name. This is not working as intended as it should require a string value that matches the team name.

Any non-matching text:

1. Navigate to a team that you can archive.
2. Type any text that is not exactly the same as the team name.
3. Press enter. You should see that the team was archived. You should see a team archived notification.

No text, just enter:

1. Navigate to a team that you can archive.
2. Do not type any text into the validation field.
3. Press enter. You should see that the team is no longer in the left nav. You may or may not see a notification that the team was archived. Segment is showing the archive event on staging.

### PR DESCRIPTION
**Pull request by dan-f**
Fixes #1511 

To verify:

- [ ] Create a team
- [ ] Navigate to that team's settings
- [ ] Click "Delete Team"
- [ ] In the input field, hit enter/return
- [ ] Note that the team isn't deleted
- [ ] type something other than the team name
- [ ] Note that the team isn't deleted
- [ ] Type the team name
- [ ] See that the team is deleted

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test No. 1 (TA) (in progress)

- [ ] Create a team
- [ ] Navigate to that team's settings
- [ ] Click "Delete Team"
- [ ] In the input field, hit enter/return
- [ ] Note that the team isn't deleted
- [ ] type something other than the team name
- [ ] Note that the team isn't deleted
- [ ] Type the team name
- [ ] See that the team is deleted

File: src/universal/modules/teamDashboard/components/ArchiveTeam/ArchiveTeamForm.js [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  handleFormBlur: () => any,
+  handleFormSubmit: () => any,
+  handleSubmit: (fn: () => any) => any,
+  teamName: string
+};
+
+class ArchiveTeamForm extends Component<Props> {
+  validate = (value) => (
+    value !== this.props.teamName
+      ? 'The team name entered was incorrect'
```
Comment (ackernaut) [inline src/universal/modules/teamDashboard/components/ArchiveTeam/ArchiveTeamForm.js]: Small thing. I would add a period at the end of the input error message since this is a sentence.

File: src/universal/modules/teamDashboard/components/ArchiveTeam/ArchiveTeamForm.js [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+      : undefined
+  );
+
+  render() {
+    const {handleFormSubmit, handleFormBlur, handleSubmit} = this.props;
+    return (
+      <form onSubmit={handleSubmit(handleFormSubmit)}>
+        <Field
```
Comment (ackernaut) [inline src/universal/modules/teamDashboard/components/ArchiveTeam/ArchiveTeamForm.js]: Just curious, do input fields get minimal a11y love, like an `aria-label`? Not in the scope of this PR, for sure. I could look it up, too. Ha! #lazyweb

File: src/universal/modules/teamDashboard/components/ArchiveTeam/ArchiveTeam.js [hunk 3]
```diff
@@ -1,68 +1,46 @@
...
+  handleFormBlur,
+  handleFormSubmit,
+  showConfirmationField,
+  teamName
+}: Props) => (
+  <div>
+    {!showConfirmationField ?
+      <div>
+        <Button
+          buttonSize="small"
```
Comment (ackernaut) [inline src/universal/modules/teamDashboard/components/ArchiveTeam/ArchiveTeam.js]: We have an `aria-label` prop now for buttons, could add here.

**Comment by dan-f** [comment]
🙏 for the review, @ackernaut! I'm gonna address your comments, and merge this thing once tests pass!

**Comment by ackernaut** [comment]
👍
