### PR TITLE
Agenda hotfix

### LINKED ISSUE #327: Agenda order processing broken
## Issue - Bug

Multiple clients in an action meeting see differing orders on the leftnav for added agenda items. It seems to correlate to whether an agenda item was created on the dashboard, or inside the meeting.

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #328: Adding new agenda item causes other user's to navigate away
## Issue - Bug

I think this is related to #327.

While holding an action meeting, if a user ads an agenda item with a sort index that is higher priority than the facilitator's current item, then everybody will navigate to the item that was just added; interrupting the meeting flow.

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by mattkrick**
fix #327
fix #328 

bonus: add in some ttfs as font backups.
Our webpack build uses file-loader for `.ttf` files, which means it'll only fetch these if the woff2 isn't available.

In the future, we may consider using the google fonts cdn for production...

### CODE REVIEW

File: src/universal/utils/getNextSortOrder.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import {SORT_STEP} from './constants';
 
 export default function getNextSortOrder(arr, sortField) {
-  // we always do a decremental sort
-  const lastEntity = arr[0];
-  return lastEntity ? lastEntity[sortField] + SORT_STEP : 0;
+  const maxVal = Math.max(...arr.map(val => val[sortField]));
```
Comment (jordanh) [inline src/universal/utils/getNextSortOrder.js]: Ahhhhhhhh. This makes sense.
