### PR TITLE
Epic2 bugfix

### LINKED ISSUE #487: Skipping updates to agenda via progress bar causes router loop
## Bug

Steps to reproduce:

- Start a meeting
- Advance to Updates
- Using the Progress Bar (as Facilitator) skip to the last user
- Now try moving on to Agenda and the browser should crash

Alt. way to reproduce:

- Start a meeting
- Advance to Updates
- Use sidebar nav to go back to Check-In
- Use sidebar nav to tap on Agenda
- Should crash the browser

(https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #553: DnD acts strangly when user filter active on team dashboard
## Issue - Bug

When a user filter is active, DnD doesn't always work well. Performance drags, and we can't always drop.

Here's a screencap:

screencap

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #592: Facilitator abandons meeting; allow others to end it
## Issue - Enhancement

See #576 and #578. This is perhaps a bugancement.

Imagine the following scenario:
1. The facilitator started the meeting to kick the tires but never ended it
2. A second user logged in to try and use Action (probably to use the team dashboard) and they see that a meeting is active
3. They join the meeting with the intention of ending it but they can't (without knowing the secret incantation)
4. Most importantly, the user didn't even realize they were not the facilitator - it just look like our software was stuck

Super frustrating!

So, what to do? Brainstorming options (in addition to the above):

1. If a meeting has been active for >24 hours, end it automatically (requiring a server task)
2. Add a button to the team dashboard modal offering to end a meeting if it has been active for > 24 hours
3. Add a button to the meeting sidebar for the same
4. Bug? If the tater is offline, shouldn't the user now become the tater?
5. Other?

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #818: highlighted team no worky
this guy again (chrome canary):
screen shot 2017-03-14 at 6 01 18 pm

### LINKED ISSUE #821: Actions list not showing in my dashboard
## Bug

- Go to My Dashboard (using 0.16.8 on prod server)
- You should see My Actions heading, but no action list (empty state or otherwise) in the column

I was able to run a quick test meeting and capture an action that showed in the summary. But it did not show in the dashboard.

**Estimated effort**: 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #824: Editing/Cursor Bug
## Issue - Bug

When trying to edit copy inside a completed card, cursor keeps moving to the bottom of the card after typing each letter.

### PR DESCRIPTION
**Pull request by mattkrick**
- [x] fix #553 (filtered DnD)
- [x] fix #592 (cron job for ending old meetings)
- [ ] fix #592 make facilitator role more obvious in meeting-- @ackernaut 
- [x] fix #487 (please test this one ultra thoroughly!)
  - [x] refactor gotoItem because I think a bug might be lurking there
  - [x] refactor the server mutation
- [x] fix #818
- [x] fix #821
- [x] fix #824

### CODE REVIEW

File: src/universal/modules/meeting/helpers/actionMeeting.js [hunk 1]
```diff
@@ -0,0 +1,58 @@
+import {LOBBY, CHECKIN, UPDATES, FIRST_CALL, AGENDA_ITEMS, LAST_CALL, SUMMARY} from 'universal/utils/constants';
+
+export default {
```
Comment (jordanh) [inline src/universal/modules/meeting/helpers/actionMeeting.js]: What you can't see, is the single tear rolling down my cheek.

Comment (mattkrick) [inline src/universal/modules/meeting/helpers/actionMeeting.js]: SPAs grow up so fast these days...

**Comment by mattkrick** [comment]
found a fun bug--
currently, we query for agendaItems when we start a meeting. that's how we know if all the agenda items have loaded yet.
However, if the team has 2 meetings back to back, then that old value is still cached. that means the meeting is broken the 2nd time around if the 2nd meeting has fewer agenda items than the first meeting.

we can't use a mutationHandler because we want to reset it for everyone.
so, we could do a few things:
- completely refactor the meeting ephemeral data onto a meeting object, that way it'd have a distinct key in the client cache
- trigger the query in the constructor so it happens everytime the meeting container gets mounted
- trigger the requery ~10seconds after they go to the summary page (similar to a zero subscription, where we basically just tell it to refetch if certain data like SUMMARY comes through)
- do nothing

**Comment by mattkrick** [comment]
wooooo got it in with 8 mins to spare! ready for approval

File: src/server/graphql/models/IntranetJobs/intranetJobsQuery.js [hunk 2]
```diff
@@ -69,5 +71,26 @@ export default {
       await Promise.all(adjustmentPromises);
       return adjustmentPromises.length;
     }
+  },
+  endOldMeetings: {
```
Comment (jordanh) [inline src/server/graphql/models/IntranetJobs/intranetJobsQuery.js]: Ah awesome, I will add this to `action-chronos`.

File: src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js [hunk 3]
```diff
@@ -153,43 +146,34 @@ export default class MeetingContainer extends Component {
...
     }
-    const facilitatorIntro = nextFacilitator.isSelf ? 'You are' : `${nextFacilitator} is`;
-    dispatch(showInfo({
-      title: `${facilitatingMember.preferredName} Disconnected!`,
-      message: `${facilitatorIntro} the new facilitator`
-    }));
+  }
+
+  componentWillReceiveProps(nextProps) {
+    electFacilitatorIfNone(nextProps, this.props.members);
```
Comment (jordanh) [inline src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js]: Ah, excellent. This will help a lot.

File: src/universal/modules/meeting/helpers/electFacilitatorIfNone.js [hunk 4]
```diff
@@ -0,0 +1,29 @@
+import {cashay} from 'cashay';
+import {showInfo} from 'universal/modules/toast/ducks/toastDuck';
+
+const electFacilitatorIfNone = (nextProps, oldMembers) => {
```
Comment (jordanh) [inline src/universal/modules/meeting/helpers/electFacilitatorIfNone.js]: I think this function could use some comments. I am having a hard time grokking what each of the state checks imply semantically. I'll give some examples:

File: src/universal/modules/meeting/helpers/electFacilitatorIfNone.js [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+  const {dispatch, team: {activeFacilitator}, members} = nextProps;
+  if (!activeFacilitator) return;
```
Comment (jordanh) [inline src/universal/modules/meeting/helpers/electFacilitatorIfNone.js]: Does this mean that the meeting hasn't started yet and a facilitator has never been elected?

File: src/universal/modules/meeting/helpers/electFacilitatorIfNone.js [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+  // if the meeting has started, find the facilitator
+  const facilitatingMemberIdx = members.findIndex((m) => m.isFacilitating);
+  const facilitatingMember = members[facilitatingMemberIdx];
+  if (!facilitatingMember || facilitatingMember.isConnected === true) return;
```
Comment (jordanh) [inline src/universal/modules/meeting/helpers/electFacilitatorIfNone.js]: Why isn't this `facilitatingMember && facilitatingMember.isConnected === true`?

File: src/universal/modules/meeting/helpers/electFacilitatorIfNone.js [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+  // check the old value because it's possible that we're trying before the message from the Presence sub comes in
+  const oldFacilitatingMember = oldMembers[facilitatingMemberIdx];
+  if (!oldFacilitatingMember || oldFacilitatingMember.isConnected === false) return;
```
Comment (jordanh) [inline src/universal/modules/meeting/helpers/electFacilitatorIfNone.js]: Why is isConnected `false` here?

File: src/universal/modules/meeting/helpers/electFacilitatorIfNone.js [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+  // if the facilitator isn't connected, then make the first connected user elect a new one
+  const onlineMembers = members.filter((m) => m.isConnected);
+  const callingMember = onlineMembers[0];
+  const nextFacilitator = members.find((m) => m.isFacilitator && m.isConnected) || callingMember;
+  if (callingMember.isSelf) {
```
Comment (jordanh) [inline src/universal/modules/meeting/helpers/electFacilitatorIfNone.js]: This is super smart and needs no comment. Super clean way to make sure only one connected member calls the mutation :)

**Comment by jordanh** [comment]
Test Plan
---

- [ ] Can reprioritize tasks on team dashboard when filter active
- [ ] Can execute cron job for ending old meetings
- [ ] Meeting facilitation:
   - [ ] Can start meeting
   - [ ] Second player can join
   - [ ] F can go forward through all phases, TMs follow
   - [ ] F can can go backward all phases, TMs follow
   - [ ] TMs can still diverge
   - [ ] Meeting summary is sent
- [ ] highlighted teams work on sidebar
- [ ] action makes its appearance again
- [ ] editing cursor annoyingly going to the end fixed/worked around

**Comment by jordanh** [comment]
So far Matt, I could only find one reproducable issue #828.

I swear I also saw the agenda list not always mark items as completed, but I could be mistaken...

**Comment by mattkrick** [comment]
that could be, i had to change the completion logic so maybe a bug got in, lemme play around more & see if i get some repro steps

**Comment by jordanh** [comment]
Kk, I'm around and mostly available today so if you want to jam on it together lemme kno. Be sweet to get this up on prod in time for our meeting. Then we can all test together :)

**Comment by mattkrick** [comment]
@jordanh can you give er another go & lemme know whatcha think?

**Comment by jordanh** [comment]
LGTM!
