### PR TITLE
Team settings fix #109

### LINKED ISSUE #109: Handle deleting a team member (post-MVP)
## Issue - Enhancement

Just a reminder that when we delete a team member from a team, we also need to remove that from the in-memory `socket.authorization` array.

The easiest way to do this is probably:
- publish `{type: KICKOUT, user: userIdToRemove}` to both `meeting/:meetingId` and `presence/:meetingId`.
- write a `PUBLISH_OUT` middleware that listens for `req.data.type === KICKOUT`. And if the `req.data.user === authToken.sub`, then we know this is the guy we should remove
- call `socket.kickOut` within that middleware
- call `next(true)` to fail silently so nothing ever goes back to the client for any of them

How critical is it that a removed team member be kicked out immediately? Probably not very, but since our server is open source, that means _The World is Watching&trade;_ so we gotta keep it tight.
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))
- **(Optional) link to mission spec:** ([duplicate and edit template](https://docs.google.com/document/d/1lgTJnJzBt9-4If883iOvthmc0hy-6C6hBF7KNN-lsXU/edit))

### PR DESCRIPTION
**Pull request by mattkrick**
Left to do:

- [x] Pop confirmation modal for remove ('Are you sure you want to remove X from the team? Once you remove a team member, all of their projects will be assigned to you')
- [x] Pop confirmation modal for promote ('Once you promote you will no longer be the team leader and cannot undo this! Are you sure?')
- [x] Pop confirmation for leave ('Once you leave the team you will need to be invited back!' 'You have 3 projects outstanding. would you like to reassign those to other team members before you leave? If not, they will all be given to the team leader')
- [x] Write remove/leave mutation (inactive, reassign projects, delete actions, delete agenda items, send new token, write TODO about blacklisting the current token OOS)
- [x] Write promote mutation (remove isLead from 1, write to another)
- [x] Invite field retains value on blur (normal behavior for inputs)
- [x] pop a toast when an invitation is sent
- [x] if email address is already in list, say 'That person is already invited/on the team!'
- [x] Cancel outstanding invitation
- [x] Resend invitation
- [x] denormalize email onto the TeamMember table
- [x] kick me off the team, unsub me, and give me a new token if i leave

### CODE REVIEW

**Comment by ackernaut** [comment]
@mattkrick I think the re-assign could be simpler:

“Once you leave the team you will need to be invited back! Your 3 projects will be assigned to the team lead.”

**Comment by mattkrick** [comment]
For invitations, we have 2 options
- 1 invitation id per email
- 1 invitation id per invitation

The difference matters when an invitation is cancelled/resent. Do we create a new document, or do we just mutate the current one. Right now, I think it'd be nice to create a new doc cuz space is cheap & then we can see how often this happens.

Next hurdle is when we resend an invitation, do we invalidate the old invite token. For security, I don't see any major difference because we already expire the old document, but I'm gonna create a new one just so I can reuse the same function.

**Comment by jordanh** [comment]
Those choices seem WAY reasonable!

**Comment by mattkrick** [comment]
@ackernaut my modals aren't lookin too hot (RemoveTeamMemberModal). Before I dove in & tore it up I wanted to pick your brain on the looks. Ideally, we could make one that darkens up the background & then if the background is clicked, we can make the modal go away (that's the `onBlur` handler being passed in). I got a few ideas on how to do it, but your styles look way nicer!

**Comment by mattkrick** [comment]
team member removal:
- set isActive to false
- remove the teamId from their User document
- send a new token without that teamId to the client
- write a hook on the websocket connect that checks the User doc before renewing the token
- kick out of any active subscriptions

i'm not in love with this because we're not blacklisting the token like we should. to do that, we'd have to set up a microservice. without that, it means the attacker (ex-teammember) can keep using the validated token for up to 30 days by manually replacing the token. that said, i think it's the best we can do for now.

**Comment by ackernaut** [comment]
@mattkrick added a checklist item for the invite field—thanks for your consideration, sir!!

**Comment by mattkrick** [comment]
really close! it's not giving me a new token & refreshing the sidebar like i expect when i leave. will wrap up tomorrow morning.

File: src/server/database/migrations/20161105214300-invitation.js [hunk 1]
```diff
@@ -0,0 +1,24 @@
+/* eslint-disable max-len */
+exports.up = async(r) => {
+  const indices = [
+    r.table('Project').indexCreate('tokenExpiration')
```
Comment (mattkrick) [inline src/server/database/migrations/20161105214300-invitation.js]: @jordanh i could go either way on this. either we index on this, or on a compound key of team & this. Using a compound key means we can remove a filter from the changefeed query

File: src/server/graphql/models/Invitation/invitationMutation.js [hunk 2]
```diff
@@ -23,9 +25,75 @@ export default {
...
+        type: new GraphQLNonNull(GraphQLID),
+        description: 'The id of the invitation'
+      },
+    },
+    async resolve(source, {inviteId}, {authToken}) {
+      await cancelInvitation(authToken, inviteId);
+      return true;
+    }
+  },
+  resendInvite: {
```
Comment (mattkrick) [inline src/server/graphql/models/Invitation/invitationMutation.js]: I still don't love this. The problem is that when I hit resend, it removes an invitation, then adds one. That's like a 1-2 second flicker. As a second pass, I'd like to just have 1 invitation per email & then we can adjust the expiration & maybe put an `inviteNumber` on it.

File: src/server/graphql/models/Invitation/invitationSubscription.js [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+    },
+    async resolve(source, {teamId}, {authToken, socket, subbedChannelName}, refs) {
+      const r = getRethink();
+      requireSUOrTeamMember(authToken, teamId);
+      const requestedFields = getRequestedFields(refs);
+      const changefeedHandler = makeChangefeedHandler(socket, subbedChannelName);
+      const now = Date.now();
+      r.table('Invitation')
+        .getAll(teamId, {index: 'teamId'})
+        .filter(r.row('tokenExpiration').ge(r.epochTime(now / 1000)))
```
Comment (mattkrick) [inline src/server/graphql/models/Invitation/invitationSubscription.js]: if we used a compound index, we could use between instead of getAll + filter.

File: src/server/graphql/models/User/userMutation.js [hunk 4]
```diff
@@ -48,13 +48,14 @@ export default {
         createdAt: new Date(userInfo.created_at),
         tms: userInfo.tms
       };
-      const {id: userId, picture, preferredName} = auth0User;
+      const {email, id: userId, picture, preferredName} = auth0User;
```
Comment (mattkrick) [inline src/server/graphql/models/User/userMutation.js]: now we've got 3 things denormalized on the teamMember.

File: src/server/graphql/models/authorization.js [hunk 5]
```diff
@@ -42,6 +43,32 @@ export const requireSUOrSelf = (authToken, userId) => {
   throw errorObj({_error: 'Unauthorized. You cannot modify another user.'});
 };
 
+export const requireSUOrSelfOrLead = async (authToken, userId, teamId) => {
```
Comment (mattkrick) [inline src/server/graphql/models/authorization.js]: When we introduce payment, we might turn tms into an array of objects with different roles, but for now, it's easy enough to just check the DB.

File: src/server/socketHandlers/scConnectionHandler.js [hunk 6]
```diff
@@ -2,23 +2,49 @@ import scSubscribeHandler from './scSubscribeHandler';
...
   return async function connectionHandler(socket) {
+    const r = getRetink();
     const authToken = socket.getAuthToken();
     const now = new Date();
     const tokenExpiration = new Date(authToken.exp * 1000);
     const timeLeftOnToken = tokenExpiration - now;
-    if (timeLeftOnToken < REFRESH_JWT_AFTER) {
+    // if the user was booted from the team, give them a new token
+    const tms = await r.table('User').get(authToken.sub)('tms');
+    const tmsIsValid = istmsValid(tms, authToken.tms);
```
Comment (mattkrick) [inline src/server/socketHandlers/scConnectionHandler.js]: when we connect, we now check the validity of the token. it's a little extra cost, but doing it once per connection is a fair price.

File: src/universal/decorators/socketWithPresence/socketWithPresence.js [hunk 7]
```diff
@@ -20,34 +23,57 @@ export default ComposedComponent => {
...
+        if (channel === TEAM) {
+          const cashayState = cashay.store.getState().cashay;
+          const team = cashayState.entities.Team && cashayState.entities.Team[teamId];
+          const teamName = team && team.name || teamId;
+          cashay.store.dispatch(showWarning({
+            title: 'So long!',
+            message: `You have been removed from ${teamName}`
+          }));
+          const {router} = this.props;
+          const onExTeamRoute = router.isActive(`/team/${teamId}`) || router.isActive(`/meeting/${teamId}`);
```
Comment (mattkrick) [inline src/universal/decorators/socketWithPresence/socketWithPresence.js]: this is the most beautiful thing i've done today.

File: src/universal/modules/teamDashboard/components/TeamSettings/TeamSettings.js [hunk 8]
```diff
@@ -3,94 +3,204 @@ import withStyles from 'universal/styles/withStyles';
...
+    };
+    const openPromoteModal = () => {
+      dispatch(togglePromoteModal(id, preferredName));
+    };
+    const openLeaveModal = () => {
+      dispatch(toggleLeaveModal(id));
+    };
+    return (
+      <div className={css(styles.actionLinkBlock)}>
+        {removeTeamMemberModal &&
```
Comment (mattkrick) [inline src/universal/modules/teamDashboard/components/TeamSettings/TeamSettings.js]: I've erred  on the side of being more repetitive for modals so that they'll be much more flexible in the future. Still not sure I like storing 3 booleans over 1 string...

File: src/universal/redux/makeReducer.js [hunk 9]
```diff
@@ -11,13 +11,27 @@ import outcomeCardReducer from 'universal/modules/outcomeCard/ducks/outcomeCardD
...
+    if (action.meta.form === formToClear) {
+      return undefined;
+    }
   }
+  return state;
 };
 
+const formPluginFactory = () => {
+  // add new fields to this array if you want em cleared
+  const clearMeAfterSubmit = ['agendaInput', 'inviteTeamMember'];
```
Comment (mattkrick) [inline src/universal/redux/makeReducer.js]: clearing inputs here on a global level saves us an additional redux action. not sure I love it.

**Comment by mattkrick** [comment]
@jordanh ready for some 👀

**Comment by jordanh** [comment]
Sweet! On it in two shakes...

File: src/universal/decorators/socketWithPresence/socketWithPresence.js [hunk 10]
```diff
@@ -20,34 +23,57 @@ export default ComposedComponent => {
...
 
+    watchForKickout() {
+      const socket = socketCluster.connect();
+      socket.on('kickOut', (error, channelName) => {
+        const {channel, variableString: teamId} = parseChannel(channelName);
+        if (channel === TEAM) {
+          const cashayState = cashay.store.getState().cashay;
+          const team = cashayState.entities.Team && cashayState.entities.Team[teamId];
+          const teamName = team && team.name || teamId;
+          cashay.store.dispatch(showWarning({
```
Comment (mattkrick) [inline src/universal/decorators/socketWithPresence/socketWithPresence.js]: i should probably use dispatch coming from the `connect`, will revise

File: src/server/graphql/models/Invitation/invitationMutation.js (hunk 2 above)
Comment (jordanh) [inline src/server/graphql/models/Invitation/invitationMutation.js]: What happens in the case where we have two team leaders (TL1 & TL2) who invite the same team member (TM)?

1. TL1 invites TM
2. 7 days later, TL2 invites TM. Won't they get error message `already invited`?

File: src/server/graphql/models/Invitation/invitationSubscription.js (hunk 3 above)
Comment (jordanh) [inline src/server/graphql/models/Invitation/invitationSubscription.js]: I imagine that the number of objects here will be low. However, might be nice to add a `TODO` comment here.

File: src/server/graphql/models/TeamMember/teamMemberMutation.js [hunk 11]
```diff
@@ -133,5 +135,97 @@ export default {
...
+        description: 'The teamMemberId of the person who is being checked in'
+      }
+    },
+    async resolve(source, {teamMemberId}, {authToken, exchange, socket}) {
+      const r = getRethink();
+      const [userId, teamId] = teamMemberId.split('::');
+      await requireSUOrSelfOrLead(authToken, userId, teamId);
+      requireWebsocket(socket);
+
+      const res = await r.table('TeamMember')
```
Comment (jordanh) [inline src/server/graphql/models/TeamMember/teamMemberMutation.js]: I ❤️  this query.

File: src/server/graphql/models/TeamMember/teamMemberMutation.js [hunk 12]
```diff
@@ -133,5 +135,97 @@ export default {
...
+      if (!promoteeOnTeam) {
+        throw errorObj({_error: `Member ${teamMemberId} is not on the team`});
+      }
+      await r.table('TeamMember')
+        // remove leadership from the caller
+        .get(myTeamMemberId)
+        .update({
+          isLead: false
+        })
+        // give leadership to the new guy
```
Comment (jordanh) [inline src/server/graphql/models/TeamMember/teamMemberMutation.js]: s/guy/person/g 😉

File: src/server/graphql/models/User/userMutation.js (hunk 4 above)
Comment (jordanh) [inline src/server/graphql/models/User/userMutation.js]: Oh wow. Tis true.

File: src/server/graphql/models/authorization.js (hunk 5 above)
Comment (jordanh) [inline src/server/graphql/models/authorization.js]: Consider adding this as a comment to this function.

File: src/server/socketHandlers/scConnectionHandler.js [hunk 13]
```diff
@@ -2,23 +2,49 @@ import scSubscribeHandler from './scSubscribeHandler';
 import scUnsubscribeHandler from './scUnsubscribeHandler';
 import scGraphQLHandler from './scGraphQLHandler';
 import {REFRESH_JWT_AFTER} from 'server/utils/serverConstants';
+import getRetink from 'server/database/rethinkDriver';
+import isObject from 'universal/utils/isObject';
+import jwtDecode from 'jwt-decode';
 
+// we do this otherwise we'd have to blacklist every token that ever got replaced & query that table for each query
+const istmsValid = (tmsFromDB, tmsFromToken) => {
```
Comment (jordanh) [inline src/server/socketHandlers/scConnectionHandler.js]: Shouldn'tThisBe isTmsValid? 😉

File: src/server/socketHandlers/scConnectionHandler.js [hunk 14]
```diff
@@ -2,23 +2,49 @@ import scSubscribeHandler from './scSubscribeHandler';
...
+  if (tmsFromDB.length !== tmsFromToken.length) return false;
+  for (let i = 0; i < tmsFromDB.length; i++) {
+    if (tmsFromDB[i] !== tmsFromToken[i]) return false;
```
Comment (jordanh) [inline src/server/socketHandlers/scConnectionHandler.js]: Are we sure that the order of these arrays will always match? We don't need to add a sort here?

File: src/universal/components/Dashboard/DashModal.js [hunk 15]
```diff
@@ -16,26 +27,56 @@ const DashModal = (props) => {
 
 DashModal.propTypes = {
   children: PropTypes.any,
+  onBackdropClick: PropTypes.func,
+
+  // NOTE: Use 'fixed' to show over 'viewport'.
```
Comment (jordanh) [inline src/universal/components/Dashboard/DashModal.js]: This is cool.

File: src/universal/components/Editable/Editable.js [hunk 16]
```diff
@@ -0,0 +1,198 @@
+import React, {Component, PropTypes} from 'react';
+import withStyles from 'universal/styles/withStyles';
+import {css} from 'aphrodite-local-styles/no-important';
+import appTheme from 'universal/styles/theme/appTheme';
+import ui from 'universal/styles/ui';
+import makePlaceholderStyles from 'universal/styles/helpers/makePlaceholderStyles';
+import FontAwesome from 'react-fontawesome';
+
+class Editable extends Component {
```
Comment (jordanh) [inline src/universal/components/Editable/Editable.js]: Oh! This is what you meant when you kept saying "we'll need to make this `Editable`". I didn't realize! Cool!

File: src/universal/decorators/socketWithPresence/socketWithPresence.js (hunk 7 above)
Comment (jordanh) [inline src/universal/decorators/socketWithPresence/socketWithPresence.js]: This is beautiful. The layers. The beautiful layers.

File: src/universal/modules/teamDashboard/components/TeamSettings/TeamSettings.js (hunk 8 above)
Comment (jordanh) [inline src/universal/modules/teamDashboard/components/TeamSettings/TeamSettings.js]: Yeah, I can see that. Fine for now, probably good fodder for a refactor in the future.

File: src/universal/redux/makeReducer.js (hunk 9 above)
Comment (jordanh) [inline src/universal/redux/makeReducer.js]: It's very magical. I'd prefer the redux action because it's more explicit. Failing that, a comment should be added to the submit handlers of each of these forms so future selves can remember where we put the magic.

File: src/server/graphql/models/Invitation/invitationMutation.js (hunk 2 above)
Comment (mattkrick) [inline src/server/graphql/models/Invitation/invitationMutation.js]: they would if they typed in the email as if it were a new invitee. however, if you scroll down to the invitee & click "resend" then it will invalidate the old token and send a new email with a new token.

File: src/server/graphql/models/authorization.js (hunk 5 above)
Comment (mattkrick) [inline src/server/graphql/models/authorization.js]: i was thinking about it, but i'm still not sure what kinda workflow we're after for payment, so it could vary depending on that design sprint.

File: src/server/graphql/models/Invitation/helpers.js [hunk 17]
```diff
@@ -124,3 +126,27 @@ export const asyncInviteTeam = async (authToken, teamId, invitees) => {
...
+  } else if (tokenExpiration < now) {
+    error.type = 'alreadyExpired';
+  }
+  if (error.type) {
+    // eslint-disable-next-line no-underscore-dangle
+    error._error = 'Cannot cancel invitation';
+    throw errorObj(error);
+  }
+  await r.table('Invitation').get(inviteId).update({
+    tokenExpiration: new Date(0),
```
Comment (mattkrick) [inline src/server/graphql/models/Invitation/helpers.js]: nonono, `Date` is a hot mess in JS. `new Date(0) !== Date(0)`. the first returns a date object of the epoch, the second returns a string of now.

File: src/server/socketHandlers/scConnectionHandler.js (hunk 13 above)
Comment (mattkrick) [inline src/server/socketHandlers/scConnectionHandler.js]: i could be swayed either way. the DOM can't even agree on how to capitalize acronyms...

File: src/server/socketHandlers/scConnectionHandler.js (hunk 14 above)
Comment (mattkrick) [inline src/server/socketHandlers/scConnectionHandler.js]: if it's not, it will be the second time :smile:

File: src/universal/components/Dashboard/DashModal.js (hunk 15 above)
Comment (mattkrick) [inline src/universal/components/Dashboard/DashModal.js]: all props to @ackernaut!

File: src/server/graphql/models/Invitation/helpers.js (hunk 17 above)
Comment (jordanh) [inline src/server/graphql/models/Invitation/helpers.js]: Wow. I just learned something here. This is a new level of disgusting. Ugh.

File: src/server/graphql/models/Invitation/invitationMutation.js (hunk 2 above)
Comment (jordanh) [inline src/server/graphql/models/Invitation/invitationMutation.js]: Got it. 👌

File: src/server/graphql/models/authorization.js (hunk 5 above)
Comment (jordanh) [inline src/server/graphql/models/authorization.js]: Fair enough!

File: src/universal/redux/makeReducer.js (hunk 9 above)
Comment (jordanh) [inline src/universal/redux/makeReducer.js]: Adding comments now..

**Comment by jordanh** [comment]
@mattkrick before merging, I did some testing using a couple of browser windows. Found some small stuff: #509, #510, #511 

I think we should also tackle #512 now, and add a part of it to the migration that's going into this PR.

After that, let's merge, merge, merge!

**Comment by jordanh** [comment]
By the way. CircleCI is dumb: https://discuss.circleci.com/t/destroy-npm-cache-node-modules-based-on-a-hash-of-package-json-or-if-present-npm-shrinkwrap-json/2985/7

**Comment by mattkrick** [comment]
@jordanh think this is ready for another look

**Comment by jordanh** [comment]
Looking now!

**Comment by jordanh** [comment]
Getting real close now! I was able to test:

- [ ] Up migration
- [ ] Down migration
- [ ] Rename a team
- [ ] Dashboard still works
- [ ] Remove existing user
- [ ] Promote to team lead

I got stuck on:

- [ ] New user invitation

Which is blocking:

- [ ] Invitation acceptance (new user)
- [ ] Invitation acceptance (new existing user)

I've opened #515 and #516.

I've got a feeling we're going to get this wrapped pretty quickly. I'm going to go ahead and migrate the latest data from production back to staging so we're in a good position to test later.

**Comment by mattkrick** [comment]
@jordanh give her another go, if there are any more issues feel free to state em here so we have a roadmap to merge for this PR.

**Comment by jordanh** [comment]
Sweet. Giving it a go now!

**Comment by jordanh** [comment]
Tested:

- [x] Up migration
- [x] Down migration
- [x] Rename a team
- [x] Dashboard still works
- [x] Remove existing user
- [x] Promote to team lead
- [x ] New user invitation
- [x] Invitation acceptance (new user)
- [x] Invitation acceptance (new existing user)

**Comment by jordanh** [comment]
I opened #518. But, I don't see that as gating merging this. Onward!
