### PR TITLE
fix registerQuery logic

### LINKED ISSUE #2700: logout 2x breaks
repro
- login, logout, login, logout. see break

AC
- [ ] can logout 2x

effort: 12 points

### PR DESCRIPTION
**Pull request by mattkrick**
fix #2700

issues found:
- code in the DashAlert would fail if the component unmounted after the store was cleared
- MyTimelineRoot has a ttl but did not have any subscriptions, which caused a queryFetcher to never get disposed of. Fixed by registering all queries with a TTL, subscriptions or not.

additional fixes:
- i brought back aggressive query caching. this means you can navigate around the site & if you go back to a page in a reasonable amount of time (5 minutes) then you won't need to requery (since the subscriptions are still active & populating the new stuff). this should make the site feel a lot faster when clicking around.

TEST
- open devtools>network>websocket frames
- go to timeline, tasks, a team, another team
- [ ] revisit each of the routes, no new queries are sent to the server
- [ ] login, logout, login, logout. no errors in the console
- [ ] filter cards on a team dashboard, it works

### CODE REVIEW

**Comment by jordanh** [comment]
# Test Cycle 1

## Tests
- open devtools>network>websocket frames
- go to timeline, tasks, a team, another team
- [ ] revisit each of the routes, no new queries are sent to the server
- [ ] login, logout, login, logout. no errors in the console
- [ ] filter cards on a team dashboard, it works

## Notes

File: src/universal/components/QueryRenderer/QueryRenderer.js [hunk 1]
```diff
@@ -353,15 +348,15 @@ function fetchQueryAndComputeStateFromProps(
...
-    ReactRelayQueryRenderer.renewTTL(queryKey)
-    if (props.subscriptions && environment.registerQuery) {
-      environment.registerQuery(
-        queryKey,
-        props.subscriptions,
-        props.subParams,
-        operation.variables,
-        queryFetcher
-      )
+    const cacheQuery = Boolean(
```
Comment (jordanh) [inline src/universal/components/QueryRenderer/QueryRenderer.js]: Stupid Javascript question: is that `Boolean()` needed with those logical operators? Is it because `environment.registeryQuery` could be undefined, and the rest will be short circuited?

Comment (mattkrick) [reply src/universal/components/QueryRenderer/QueryRenderer.js]: it's not necessary, i just do it so typescript knows it's a boolean, otherwise it would be `undefined | number`
