### PR TITLE
fix #513 fix #543

### LINKED ISSUE #513: Pop a toast to all connected users when someone joins their team?
a little nice to have, whatcha think?

### LINKED ISSUE #543: Unable to end meeting
## Issue - Bug

Whoa! Just caught this one on production giving a demo to my friend:

Steps to reproduce:

1. Start a meeting
2. Create one agenda item
3. Create one project
4. At last call, end meeting

Here's the stack trace from the server:

```
2016-11-26T23:34:55.418242980Z app[web.1]:     message: 'Expected type ARRAY but found OBJECT in:\nr.table("Meeting").getAll("ryrERv6xg", {\n    index: "teamId"\n}).orderBy(r.desc("createdAt")).nth(0)("id").do(function(var_1837) {\n    return {\n        meetingId: var_1837,\n        meetingUpdates: r.table("AgendaItem").getAll("ryrERv6xg", {\n            index: "teamId"\n        }).filter({\n            isActive: true,\n            isComplete: true\n        }).map(function(var_1838) {\n            return var_1838("id")\n        }).coerceTo("array").do(function(var_1839) {\n            return r.table("Action").getAll(r.args(var_1839), {\n                index: "agendaId"\n            }).filter(function(var_1840) {\n                return var_1840("content").eq(null)\n            }).delete()\n        }).do(function(var_1841) {\n            return r.table("Project").getAll(r.args(var_1841), {\n                                             ^^^^^^^^^^^^^^^^  ^\n                index: "agendaId"\n                ^^^^^^^^^^^^^^^^^\n            }).filter(function(var_1842) {\n            ^                             \n                return var_1842("content").eq(null)\n            }).delete()\n        }).do(function(var_1843) {\n            return {\n                actions: r.table("Action").getAll(r.args(var_1843), {\n                    index: "agendaId"\n                }).filter(function(var_1844) {\n                    return var_1844("content").ne(null)\n                }).map(function(var_1845) {\n                    return var_1845.merge({\n                        id: var_1837.add("::").add(var_1845("id"))\n                    })\n                }).pluck("id", "content", "teamMemberId").coerceTo("array"),\n                agendaItemsCompleted: var_1843.count(),\n                projects: r.table("Project").getAll(r.args(var_1843), {\n                    index: "agendaId"\n                }).filter(function(var_1846) {\n                    return var_1846("content").ne(null)\n                }).map(function(var_1847) {\n                    return var_1847.merge({\n                        id: var_1837.add("::").add(var_1847("id"))\n                    })\n                }).pluck("id", "content", "status", "teamMemberId").coerceTo("array")\n            }\n        })\n    }\n}).do(function(var_1848) {\n    return r.table("Meeting").get(var_1848("meetingId")).update({\n        actions: var_1848("meetingUpdates")("actions").default([]),\n        agendaItemsCompleted: var_1848("meetingUpdates")("agendaItemsCompleted").default(0),\n        endedAt: r.ISO8601("2016-11-26T23:34:55.399Z"),\n        facilitator: "google-oauth2|112540584686400405659::ryrERv6xg",\n        successExpression: "Great job",\n        successStatement: "Making progress, little by little!",\n        invitees: r.table("TeamMember").getAll("ryrERv6xg", {\n            index: "teamId"\n        }).filter({\n            isNotRemoved: true\n        }).coerceTo("array").map(function(var_1849) {\n            return {\n                id: var_1849("id"),\n                present: r.branch(var_1849("isCheckedIn").eq(true), true, false)\n            }\n        }),\n        projects: var_1848("meetingUpdates")("projects").default([])\n    }, {\n        nonAtomic: true\n    })\n})\n',
2016-11-26T23:34:55.418320063Z app[web.1]:     locations: [ [Object] ],
2016-11-26T23:34:55.418327660Z app[web.1]:     path: [ 'endMeeting' ] } ]
2016-11-26T23:35:10.959672864Z app[web.1]: Client disconnected: V1hXeCUMU830xqTFAAJU
```

Will triage tomorrow for a hotfix...

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by mattkrick**

### CODE REVIEW

**Comment by mattkrick** [comment]
it:
- [ ] pops a toast to all team members when a user joins the team
- [ ] does not pop a toast to the new member
- [ ] fixes #543 and lets you finish a meeting

File: src/server/graphql/models/TeamMember/teamMemberMutation.js [hunk 1]
```diff
@@ -136,18 +137,23 @@ export default {
...
         );
       const tms = oldtms.concat(teamId);
       const asyncPromises = [
         dbWork,
         auth0ManagementClient.users.updateAppMetadata({id: userId}, {tms})
       ];
-      await Promise.all(asyncPromises);
+      const [userEmail] = await Promise.all(asyncPromises);
+      const payload = {type: JOIN_TEAM, name: userEmail};
+      exchange.publish(`${PRESENCE}/${teamId}`, payload);
```
Comment (jordanh) [inline src/server/graphql/models/TeamMember/teamMemberMutation.js]: Hey, socketCluster is pretty cool!

File: src/server/worker.js [hunk 2]
```diff
@@ -56,11 +56,12 @@ export function run(worker) {
   }
 
   // HTTP GraphQL endpoint
+  const graphQLHandler = httpGraphQLHandler(scServer.exchange);
```
Comment (jordanh) [inline src/server/worker.js]: I bet this will be useful for other features later, too. 👏

File: src/universal/decorators/socketWithPresence/socketWithPresence.js [hunk 3]
```diff
@@ -38,20 +44,35 @@ export default ComposedComponent => {
...
+    watchForJoin(teamId) {
+      const socket = socketCluster.connect();
+      const channelName = `${PRESENCE}/${teamId}`;
+      const {dispatch} = this.props;
+      socket.watch(channelName, (data) => {
+        if (data.type === JOIN_TEAM) {
+          const {name} = data;
+          const teamName = getTeamName(teamId);
+          dispatch(showInfo({
+            title: 'The fun has arrived!',
```
Comment (jordanh) [inline src/universal/decorators/socketWithPresence/socketWithPresence.js]: I am going to tweak this message slightly...

**Comment by jordanh** [comment]
Tests:

- [ ] pops toast on team member accepting invitation (verify #513)
- [ ] can end meeting (verify fix #543)

**Comment by jordanh** [comment]
Ah, I see your tests above! Will tick off your list...

**Comment by jordanh** [comment]
Opened #545 (but 👌  to merge without discussion or fix)

**Comment by jordanh** [comment]
All tests complete! Looks great. Thank you for fixing that regression so quickly @mattkrick!
