### PR TITLE
Fix timer bug

### LINKED ISSUE #3294: Timer resets when navigate away from phase
Repro:
- [ ] facilitator sets timer to 5 mins in reflect phase
- [ ] facilitator goes back to check-in round
- [] facilitator goes back to reflect phase, timer is back at 5 mins

TEST
- [ ] works as expected

AC: 10.5

### PR DESCRIPTION
**Pull request by mattkrick**
fix #3294 

timers are difficult because we can't trust the client clock
we could send a message every second from the server updating the time, but that's pretty inefficient
instead, we can calculate the client clock offset & then from that determine how much time is remaining. to do that, we need to know what time the server thinks it is & how long ago it thought that.
we assume a message takes 200ms to make it to the client, so we take the server time, add 200ms and diff that against the client clock. that's our new scheduled end time.

TEST
- [ ] start a retro with 2 people
- [ ] go to reflect phase
- [ ] facilitator adds a 5:00 timer
- [ ] participant sees timer start
- [ ] participant goes back to check in round & stays there for 5 seconds
- [ ] participant goes back to reflect phase, timer is the same as the facilitator's timer (+/- 1 second)
- [ ] facilitator goes back to check in round & then back to reflect phase, timer is still valid
- [ ] facilitator can refresh & timer is valid
- [ ] facilitator can cancel the timer & it goes away for everyone

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test Cycle No. 1
- [ ] start a retro with 2 people
- [ ] go to reflect phase
- [ ] facilitator adds a 5:00 timer
- [ ] participant sees timer start
- [ ] participant goes back to check in round & stays there for 5 seconds
- [ ] participant goes back to reflect phase, timer is the same as the facilitator's timer (+/- 1 second)
- [ ] facilitator goes back to check in round & then back to reflect phase, timer is still valid
- [ ] facilitator can refresh & timer is valid
- [ ] facilitator can cancel the timer & it goes away for everyone

File: packages/client/utils/relay/LocalTimeHandler.ts [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+    const timeRemaining = record.getValue('timeRemaining')
+    if (!scheduledEndTimeStr || !timeRemaining) {
+      record.setValue(null, 'localScheduledEndTime')
+      return
+    }
+    const scheduledEndTime = new Date(scheduledEndTimeStr).getTime()
+    const clientClockOffset =
+      (viewer.getValue('clientClockOffset') as number) ||
+      setClientClockOffset(viewer, scheduledEndTime, timeRemaining)
+    console.log('clock offset', clientClockOffset)
```
Comment (ackernaut) [inline packages/client/utils/relay/LocalTimeHandler.ts]: Yank console log

**Comment by ackernaut** [comment]
Looks good! One line to remove
