### PR TITLE
Elect new facilitator fix #438 fix #447

### LINKED ISSUE #438: TypeError: Cannot read property 'id' of undefined
https://sentry.io/parabol/action-production/issues/173835794/

```
TypeError: Cannot read property 'id' of undefined
  at checkCanDelete (/static/app_99426fdb3a734ccd8de2.js:6994:18)
  at processSubscriptionDoc (/static/app_99426fdb3a734ccd8de2.js:7024:23)
  at mergeNewData (/static/app_99426fdb3a734ccd8de2.js:3072:65)
  at remove (/static/app_99426fdb3a734ccd8de2.js:3190:11)
  at SCEmitter.<anonymous> (/static/0_21e74a6f329f56f1ec42.js:8555:7)
...
(9 additional frame(s) were not displayed)
```

### LINKED ISSUE #447: Unable to logout and login properly
## Issue - Bug

When you logout and log back in, the user screen renders like this:

image

The good news is, its reproducible locally:

Steps to reproduce:

   1. Run `npm run dev`
   1. Clear your localstorage
   1. Log in
   1. From any dashboard, click on the gear and log out
   1. Log back in
   1. Observe failure

This one appears to be new with v0.9.4.

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by mattkrick**
This also fixes that weird bug that @jordanh found where I clicked start & he became facilitator. 

i also cleaned up aphrodite just cuz.

### CODE REVIEW

File: src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js [hunk 1]
```diff
@@ -152,6 +153,23 @@ export default class MeetingContainer extends Component {
...
+    if (activeFacilitator) {
+      // if the meeting has started, find the facilitator
+      const facilitatingMember = members.find((m) => m.isFacilitating);
+      if (facilitatingMember && facilitatingMember.isConnected === false) {
+        // if the facilitator isn't connected, then make the first connected guy elect a new one
+        const onlineMembers = members.filter((m) => m.isConnected);
+        if (onlineMembers[0].isSelf) {
+          const firstFacilitator = members.find((m) => m.isFacilitator && m.isConnected) || onlineMembers[0];
+          const options = {variables: {facilitatorId: firstFacilitator.id}};
+          cashay.mutate('startMeeting', options);
```
Comment (jordanh) [inline src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js]: Does this restart the meeting?

File: src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js [hunk 2]
```diff
@@ -152,6 +153,23 @@ export default class MeetingContainer extends Component {
...
+  componentWillReceiveProps(nextProps) {
+    // make sure we still have a facilitator. if we don't elect a new one
+    const {team: {activeFacilitator}, members} = nextProps;
+    if (activeFacilitator) {
+      // if the meeting has started, find the facilitator
+      const facilitatingMember = members.find((m) => m.isFacilitating);
+      if (facilitatingMember && facilitatingMember.isConnected === false) {
+        // if the facilitator isn't connected, then make the first connected guy elect a new one
+        const onlineMembers = members.filter((m) => m.isConnected);
+        if (onlineMembers[0].isSelf) {
```
Comment (jordanh) [inline src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js]: This is a good solution!

File: src/server/graphql/models/Team/teamMutation.js [hunk 3]
```diff
@@ -420,6 +420,29 @@ export default {
       // TODO: trigger welcome email
     }
   },
+  changeFacilitator: {
```
Comment (jordanh) [inline src/server/graphql/models/Team/teamMutation.js]: Where does this end up getting called from?

File: src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js [hunk 4]
```diff
@@ -16,7 +16,7 @@ const createStartMeetingHandler = (members) => () => {
   if (!self) {
     throw new Error('You are not a member! How can that be?');
   }
-  const firstFacilitator = members.find(member => member.isFacilitator);
+  const firstFacilitator = members.find((m) => m.isFacilitator && m.isConnected);
```
Comment (jordanh) [inline src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js]: I see `isFacilitating` elsewhere, is it `isFacilitator` here?

File: src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js [hunk 5]
```diff
@@ -16,7 +16,7 @@ const createStartMeetingHandler = (members) => () => {
...
   const safeFirstFacilitator = firstFacilitator || self;
   const facilitatorId = self.isFacilitator ? self.id : safeFirstFacilitator.id;
```
Comment (jordanh) [inline src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js]: same ting

File: src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js (hunk 1 above)
Comment (mattkrick) [inline src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js]: oh that's a fantastic catch! a lil debugging remnant. I'll change this

File: src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js (hunk 4 above)
Comment (mattkrick) [inline src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js]: yep, `isFacilitator` is a property of teamMember. We'll be able to adjust that in team settings. This looks confusing. lemme rewrite.

**Comment by mattkrick** [comment]
@jordanh whattup with that failing CI? bcrypt givin us crap?

**Comment by jordanh** [comment]
Yeah, bcrypt giving us crap. You have to go to the CircleCI build and select "Rebuild without cache."

image

It should save the new cache once the tests complete successfully... (so I'm told) :)

**Comment by jordanh** [comment]
Ah, I see why. This branch [inherited the cache from master](https://circleci.com/docs/how-cache-works/). I need to clear the cache for the last master build and then subsequent builds won't run into this issue any longer.

**Comment by jordanh** [comment]
Now it looks like it's just lint...

File: src/server/graphql/models/Team/teamMutation.js (hunk 3 above)
Comment (mattkrick) [inline src/server/graphql/models/Team/teamMutation.js]: it now correctly gets called from the first present meeting attendant

File: src/universal/containers/Action/ActionContainer.js [hunk 6]
```diff
@@ -30,7 +29,7 @@ export default class ActionContainer extends Component {
   componentWillMount() {
     const {dispatch, location: {pathname: nextPage}} = this.props;
     updateAnalyticsPage(dispatch, '', nextPage);
-    injectGlobals(injectStyleOnce, globalStyles);
+    injectGlobals(globalStyles);
```
Comment (mattkrick) [inline src/universal/containers/Action/ActionContainer.js]: if the function is in-house, might as well import it there

File: src/universal/modules/meeting/components/AvatarGroup/AvatarGroup.js [hunk 7]
```diff
@@ -16,7 +16,7 @@ const AvatarGroup = (props) => {
       {
         avatars.map((avatar, index) =>
           <div className={css(styles.item)} key={index}>
-            <Avatar {...avatar} size="small" hasBadge hasBorder={avatar.isFacilitator} />
+            <Avatar {...avatar} size="small" hasBadge hasBorder={avatar.isFacilitating} />
```
Comment (mattkrick) [inline src/universal/modules/meeting/components/AvatarGroup/AvatarGroup.js]: isFacilitator = has the privilege attached to the teamMember document.
isFacilitating = the active facilitator

File: src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js [hunk 8]
```diff
@@ -71,6 +73,7 @@ const mapStateToProps = (state, props) => {
 
 @requireAuth
 @connect(mapStateToProps)
+@maintainSocket
```
Comment (mattkrick) [inline src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js]: cancels a destruction if one exists. 
when the component unmounts, it checks to see if a socket is used anywhere else. if this is the last hoc standing, then it starts a new countdown.

File: src/server/graphql/models/Team/teamMutation.js [hunk 9]
```diff
@@ -328,7 +329,9 @@ export default {
                   });
             })
             );
-        });
+        })
+        .run();
+      }, 5000);
```
Comment (jordanh) [inline src/server/graphql/models/Team/teamMutation.js]: Ah, this old chestnut.

File: src/universal/modules/meeting/components/AvatarGroup/AvatarGroup.js (hunk 7 above)
Comment (jordanh) [inline src/universal/modules/meeting/components/AvatarGroup/AvatarGroup.js]: 👍

File: src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js (hunk 8 above)
Comment (jordanh) [inline src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js]: Although, I can't reproduce it reliably... darn it.

**Comment by jordanh** [comment]
Just tested the facilitator election logic. It's _so_ dope sir.

File: src/universal/utils/makeHref.js [hunk 10]
```diff
@@ -1,7 +1,9 @@
...
+import makeSSRAppLink from 'server/utils/makeAppLink';
+
+export default function makeHref(relativeLink) {
   if (typeof window !== 'undefined') {
     return `${window.location.origin}${relativeLink}`;
   }
-  // default for SSR/error catching
-  return 'https://www.parabol.co';
+  // default for SSR
+  return makeSSRAppLink(relativeLink);
```
Comment (mattkrick) [inline src/universal/utils/makeHref.js]: oh fo sho! it'll make our test coverage go down since it shouldn't ever get called, but we ain't got no test coverage.

File: src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js (hunk 8 above)
Comment (mattkrick) [inline src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js]: hmmmmmmm

Comment (mattkrick) [inline src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js]: ah, that makes sense. i'll fix it up!

**Comment by mattkrick** [comment]
alrighty @jordanh i'm happy with this. feel free to merge!

**Comment by jordanh** [comment]
I am confused by that uglify build failure...

**Comment by mattkrick** [comment]
i bumped the yarn.lock, did that kill it?

**Comment by jordanh** [comment]
Checking...

**Comment by mattkrick** [comment]
i wonder if the latest webpack fixes this... lemme see if happypack supports the latest webpack build. we were staying at beta22 to keep happypack

**Comment by mattkrick** [comment]
`function makeAppLink(location = '', qsMap) {`

it don't like the `location = ''` bit. not at all!

**Comment by mattkrick** [comment]
https://github.com/mishoo/UglifyJS2/issues/1349

**Comment by mattkrick** [comment]
yay it's green!
