### PR TITLE
timeline fixes

### LINKED ISSUE #2641: timeline send more initially
AC
- [ ] 2x the initial timeline items so tall screens can refresh

effort: 10.5 points

### LINKED ISSUE #2668: Exclude Dash Alert from Sidebar
Today, the Dash Alert sits above the sidebar + content panel. this looks really bad when the sidebar is fixed & the window is scrollable.

AC
- [ ] Dash Alert is a child of the panel

Effort: 11 points

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] have more than 10 events on your timeline (seed or run a bunch of meetings)
- [ ] start a meeting & visit the timeline. when you scroll the timeline, you see the meeting alter follow you fix #2668
- [ ] turn your zoom to 50%-ish so the 10 timeline items don't reach the bottom of the timeline view with a fully expanded window.when you load the screen, a 2nd fetch is sent to populate the entire screen. (before, on tall screens there was no way to fetch more than the first 10) fix #2641

### CODE REVIEW

**Comment by jordanh** [comment]
# Test Cycle 1

## Tests
- [ ] have more than 10 events on your timeline (seed or run a bunch of meetings)
- [ ] start a meeting & visit the timeline. when you scroll the timeline, you see the meeting alter follow you fix #2668
- [ ] turn your zoom to 50%-ish so the 10 timeline items don't reach the bottom of the timeline view with a fully expanded window.when you load the screen, a 2nd fetch is sent to populate the entire screen. (before, on tall screens there was no way to fetch more than the first 10) fix #2641

## Notes

File: src/universal/components/TimelineFeedList.tsx [hunk 1]
```diff
@@ -2,25 +2,28 @@ import {TimelineFeedList_viewer} from '__generated__/TimelineFeedList_viewer.gra
...
 }
 
 class TimelineFeedList extends Component<Props> {
-  componentDidMount () {
-    window.addEventListener('scroll', this.onScroll)
+  intersectionObserver!: IntersectionObserver
+  lastItemRef?: HTMLDivElement
+  constructor (props: Props) {
+    super(props)
+    this.intersectionObserver = new IntersectionObserver((entries) => {
```
Comment (jordanh) [inline src/universal/components/TimelineFeedList.tsx]: Interesting!

File: src/universal/types/constEnums.d.ts [hunk 2]
```diff
@@ -8,3 +8,9 @@ export const enum LoaderSize {
   WHOLE_PAGE = 400,
   PANEL = 200
 }
+
+// equal to utils/constants
```
Comment (jordanh) [inline src/universal/types/constEnums.d.ts]: why assert the equality with a comment instead of importing `utils/constants` and using the symbols directly to define the values of the enum instead?

Comment (mattkrick) [reply src/universal/types/constEnums.d.ts]: a `const enum` requires a string or number for a value, no imports allowed.
i'm not 100% sure why this is a constraint.

they're such a nice feature though because at compile time we're left with just strings, no imports & no .d.ts file.
