### PR TITLE
Move between completed agenda items without bouncing back

### LINKED ISSUE #1660: Agenda nav bug
## Bug

No concrete reproduction steps on this one yet. @ackernaut has seen it too.

### How it manifests

When you are the facilitator and you click on

image

The UI advances to the next agenda item and then "bounces" back to the previous item. The only way to advance is by clicking the next item from the agenda list.

### PR DESCRIPTION
**Pull request by dan-f**
Fixes #1660 and #1651 

To verify:

On `master` (failing) and `fix-agenda-nav-bounce` (passing) attempt the following:

- Run a meeting
- Move to the agenda
- Add several agenda items
- Navigate through all the items out-of-order that they're marked as completed
- Navigate back through the completed items
- Complete the meeting
- On `master`, expect to experience the bouncing. Also expect that once you complete the meeting, you see all the completed agenda items still on the team dashboard.
- On `fix-agenda-nav-bounce`, expect not to experience the bouncing; expect the intuitive behavior. Also expect that once you complete the meeting, the completed agenda items are gone from the team dashboard.

### CODE REVIEW

**Comment by dan-f** [comment]
By the way, I'm continuing development here. There's a whole bag of bugs with respect to navigating between agenda items.

File: src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js [hunk 1]
```diff
@@ -247,29 +245,7 @@ class MeetingContainer extends Component {
...
 
   gotoAgendaItem = (idx) => async () => {
-    const {atmosphere, viewer: {team: {activeFacilitator, agendaItems, facilitatorPhase}}, myTeamMemberId} = this.props;
-    const isFacilitating = activeFacilitator === myTeamMemberId;
-    const facilitatorPhaseInfo = actionMeeting[facilitatorPhase];
-    const agendaPhaseInfo = actionMeeting[AGENDA_ITEMS];
-    const firstIncompleteIdx = agendaItems.findIndex((a) => a.isComplete === false);
-    const nextItemIdx = firstIncompleteIdx + (facilitatorPhase === AGENDA_ITEMS ? 1 : 0);
-    const shouldResort = facilitatorPhaseInfo.index >= agendaPhaseInfo.index && idx > nextItemIdx && firstIncompleteIdx > -1;
-    if (isFacilitating && shouldResort) {
```
Comment (dan-f) [inline src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js]: To be honest, I have no idea what was going on here other than it was resorting the agenda list in odd ways as you clicked through some (but not all) agenda items. Removing this block of code fixed it 🤷‍♂️

Comment (mattkrick) [reply src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js]: this handles float precision failure. not critical code, but without it, folks run the risk of not being able to drag & drop something more than ~40 times.

**Comment by mattkrick** [comment]
i don't care about the float precision resort, i'd rather just push something to production, so this LGTM.

A small nit is that an agenda item is marked as complete even if you go to a previous one. it should only be marked as complete if you move forward. again, don't really care, i'd rather push something to prod & fix it later. merging!

File: src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js (hunk 1 above)
Comment (dan-f) [reply src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js]: Captured here: https://github.com/ParabolInc/action/issues/1700

**Comment by dan-f** [comment]
Thx! I opened an issue for the floating point precision issue: https://github.com/ParabolInc/action/issues/1700

> A small nit is that an agenda item is marked as complete even if you go to a previous one. it should only be marked as complete if you move forward.

This is interesting. I'm not sure if I agree or not, but feel free to make a story it if it's an issue for you.
