### PR TITLE
bugfixes (fix #260 fix #241 fix #188 fix #233 fix #231 fix #119)

### LINKED ISSUE #119: UserHub overflowing it's container
## Issue - Bug

The UserHub is overflowing it's container. I noticed this a little while ago, but am just getting around to open an issue for it.

image

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### LINKED ISSUE #188: Handling `editing` in UserDash
shared `editing` status in the team dashboard works great. BUT, that same task might be viewed from a UserDash. If that occurs, the person won't see that someone else is editing it. In order to enable this, we'd have to subscribe to presence for every teamMember from every team. Is this something we want to support?

### LINKED ISSUE #231: Welcome Wizard Step 1 should pull nickname from auth0
This is especially useful for OAuth2 stuff

### LINKED ISSUE #233: "My Teams" on the dashboard sidebar should not have a caret icon
It should either be a clickable landing page, or for now, just use the regular cursor.

### LINKED ISSUE #241: In the meeting, the parabol name in upper left should goto team dash

### LINKED ISSUE #260: Authentication not completely cleaned-up on logout?
## Issue - Bug

Steps to reproduce:

1. Login as test user (e.g. `jordan@parabol.co`)
2. Logout using gear menu on dashboard
3. **Sign-up** as new user
4. Proceed through welcome wizard
5. Observe auth failures on server console

- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by mattkrick**

### CODE REVIEW

File: src/universal/decorators/loginWithToken/loginWithToken.js [hunk 1]
```diff
@@ -28,12 +29,6 @@ export default ComposedComponent => {
 
   TokenizedComp.propTypes = {
     auth: PropTypes.object,
-    user: PropTypes.shape({
```
Comment (jordanh) [inline src/universal/decorators/loginWithToken/loginWithToken.js]: oh, duh, this makes a lot of sense.

File: src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js [hunk 2]
```diff
@@ -116,7 +118,7 @@ export default class MeetingContainer extends Component {
     const {localPhaseItem, params, router, team} = props;
     const {localPhase} = params;
     // subscribe to all teams, but don't do anything with that open subscription
-    cashay.subscribe('teams');
+    cashay.subscribe(TEAMS);
```
Comment (jordanh) [inline src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js]: Mucho mejor

File: src/universal/redux/storageMerger.js [hunk 3]
```diff
@@ -9,26 +7,22 @@ export default function merger(initialState, persistedState) {
...
+        const {User} = value.entities || {};
+        value.entities = User ? {User} : {};
+        value.result = {};
+
+        // cashay now supports rehydrating sub data, but this can't account for removed items
         // remove items with unbounded growth in production
-        value.result.presence = undefined;
-        value.entities.Presence = undefined;
-        value.entities.Task = undefined;
+        // value.result.presence = undefined;
```
Comment (jordanh) [inline src/universal/redux/storageMerger.js]: @mattkrick do you need a different comment here now? Were these supposed to be commented out?

Comment (mattkrick) [inline src/universal/redux/storageMerger.js]: man, i'm so confused with the utility of persisted docs.
Any `result` from a subscription can't be trusted when the connection is lost because during that lost connection, that document could have been removed.(see #166 for how to fix this in the future).
When we get a `remove` from the server, we can't remove it from the client, because rethinkDB could send us an `ADD` (to another channel) and then a `REMOVE` (from the old channel). That means entities have unbounded growth. to mitigate this, we need TTL for docs, but since we don't have that right now, i just nuke all entities (except for `User` because cmon, how many people could you possibly log in as? Plus, that's how we get the name, picture, etc.)
